# Generated by Django 5.1.6 on 2025-03-03 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_remove_hospital_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributionrecord',
            old_name='allocated_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='distributionrecord',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='demand_gloves',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='demand_masks',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='demand_syringes',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='demand_ventilators',
        ),
        migrations.RemoveField(
            model_name='medicalsupply',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='medicalsupply',
            name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='distributionrecord',
            name='supply_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='distributionrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalsupply',
            name='total_quantity',
            field=models.IntegerField(default='timezone.now'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
