# Generated by Django 5.1.6 on 2025-03-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('demand_masks', models.IntegerField(default=0)),
                ('demand_gloves', models.IntegerField(default=0)),
                ('demand_syringes', models.IntegerField(default=0)),
                ('demand_ventilators', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_quantity', models.IntegerField()),
                ('cost_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.hospital')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.medicalsupply')),
            ],
        ),
    ]
