# Generated by Django 5.1.6 on 2025-03-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalsupply',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='total_quantity',
            field=models.IntegerField(),
        ),
    ]
