# Generated by Django 5.1.6 on 2025-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='location',
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='cost_per_unit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='medicalsupply',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
