# Generated by Django 5.1.6 on 2025-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_alter_medicalsupply_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
