# Generated by Django 5.1.6 on 2025-03-03 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_rename_allocated_quantity_distributionrecord_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionrecord',
            name='supply',
        ),
        migrations.AlterField(
            model_name='distributionrecord',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distributionrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
