# Generated by Django 5.1.6 on 2025-03-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_remove_distributionrecord_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalsupply',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
