# Generated by Django 5.1.6 on 2025-03-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_alter_medicalsupply_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
